version: '3.8'
services:
  app:
    image: etri-dips-workflow:latest
    container_name: etri-dips-workflow
    build: .
    ports:
      - '8080:5173'
    environment:
      - HOST=0.0.0.0

  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"  # Nginx의 80 포트를 호스트의 80 포트로 매핑
    volumes:
      - /home/ubuntu/nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Nginx 설정 파일을 컨테이너로 마운트
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
